### ISSUE TITLE
Having issues on the following website..

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#100175]
@fisforfaheem commented on [Fri Nov 12 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1885)

torrentgalaxy and watchcartoononline.io  Please fix issues.... torrent galaxy is redirecting upon click anywhere...and the later had weird video playback issues please se

**Comment by Yuki2718** [comment]
> torrentgalaxy and watchcartoononline.io

torrentgalaxy should have fixed in https://github.com/AdguardTeam/AdguardFilters/issues/99901 `watchcartoononline.io` redirecte me to `www.wcostream.com` and I see no playback issue.
@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr Pls take a look.

**Comment by fisforfaheem** [comment]
yes, But do take another look at torrentgalaxy.to as well... and
https://fmmods.com/* as well*

**Comment by fisforfaheem** [comment]
I am still getting redirects  I also reinstall adgaurd as well: to this
website https://bleaborahm.one/N3NmWHFWEQss

**Comment by Yuki2718** [comment]
> yes, But do take another look at torrentgalaxy.to

No redirect on my end.

> and https://fmmods.com/* as well*
> https://bleaborahm.one/N3NmWHFWEQss

Please, can you open issues separately? One URL for one issue

**Comment by Yuki2718** [comment]
I see no problem on `https://fmmods.com/` except for a leftover of cookie consent.

**Comment by Yuki2718** [comment]
@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr Please check and give him proper instruction.

**Comment by Alex-302** [comment]
@fisforfaheem Hi. Please send report using reporting tool as described here
https://kb.adguard.com/technical-support/reporting-tool
All settings will be attached automatically.
