### ISSUE TITLE
www.target.com - page loads but it is unresponsive when tapping links and buttons within it

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1008]
@Alex-302 you'll have to use VPN to access it.

The bug is iOS specific.

**Comment by Alex-302** [comment]
Can't reproduce in Safari(useragent - iOS 8.1) with US VPN. Maybe the problem only on the real device?

**Comment by TPS** [comment]
I've much the same issue on Android 4.4.2 under VPN: nav links functional, but product links blank out.…

**Comment by Alex-302** [comment]
@TPS 
please make the screenshot and select broken links. Which filters are you using?

**Comment by ameshkov** [comment]
@TPS huh, I thought you're somewhere inside US:)

**Comment by TPS** [comment]
@ameshkov Of course!  I actually live ~5 minutes from an actual brick-&-mortar Target, & they keep their inventory online, so this is important to me! ☺

@Alex-302 I'm using all filters, _except_ "Useful Ads." I'm not sure what to give you a screenshot _of_.  What happens is that when I choose _any_ product link, the whole central/content part of the page blanks out, & doesn't come back 'til I close the tab & reopen the homepage — simply pressing back does nothing. ___N.B.___:  I forgot to mention this only happens with me on *m*.target.com (mobile interface) — *www*.target.com is just fine!

**Comment by ameshkov** [comment]
Ah, I've misunderstood the "under VPN" phrase:)

I suppose this about is about mobile version of target.com as it's from AG for iOS user.

**Comment by Alex-302** [comment]
@TPS 
I can't reproduce this problem in Safari on Mac with UserAgent=iOS.
@ameshkov 
maybe the problem actual only for real devices?

**Comment by TPS** [comment]
Try log sent via ticket# FCG-302-81925 ;  does it help?

**Comment by ameshkov** [comment]
@TPS log file is empty, seems that it was cleaned up by something.

Could you please do it again with "Record HTTP requests" logging level?

**Comment by TPS** [comment]
Can't send error log! @ameshkov, Did you all fiddle with feedback mechanism with this last beta?

**Comment by ameshkov** [comment]
@TPS 
> Did you all fiddle with feedback mechanism with this last beta?

Yep, we did. It is now compressed.

Could you please get the log file manually?
I'll check what's wrong with it.

**Comment by TPS** [comment]
Sending requested log directly to you:  should have info for
https://github.com/AdguardTeam/ExperimentalFilter/issues/1008#issuecomment-163543873,
https://github.com/AdguardTeam/AdguardForAndroid/issues/186, & new, unfiled
bug regarding the bug reporting.…


-- 

https://zhjf9h10ji3.ting.com/

**Comment by ameshkov** [comment]
Now it is fixed, thank you!
https://github.com/AdguardTeam/AdguardForAndroid/issues/224

**Comment by TPS** [comment]
@Alex-302 Is the log I sent earlier sufficient, or do you need something else from me?  I'm still having this problem....

**Comment by Alex-302** [comment]
@TPS 
you wrote "Can't send error log!"
Please resend it(new).

**Comment by ameshkov** [comment]
Ops, my bad, missed that email. @Alex-302 i've sent the log to you in slack, please take a look

**Comment by Alex-302** [comment]
I see the same blocked requests, but still can't reproduce the problem.
@TPS can you try without Spyware filter?
If you have the Android SDK, I can connect to your PC and fix the problem.

Also you can disable all filters, and enable them one-by-one with checking. When you find the problem filter, disable all filters except found filter, and make new log.
