### ISSUE TITLE
hotmovs.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12579]
**Site**: https://hotmovs.com/videos/416445/brazilian-milf-2/?promo=10306

**Issue**: Please remove the Ad text seen on the page.

**Screenshot**: http://prntscr.com/imlu3g

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
A gentle reminder guys

**Comment by BlazDT** [comment]
Not reproduced. Please try this rule:

`hotmovs.com###under-pl-ad`

**Comment by Nzzyme** [comment]
Not resolved. Still seeing the string.

http://prntscr.com/j71z4m

**Comment by BlazDT** [comment]
Reproduced after clicking on comments.

**Comment by Nzzyme** [comment]
**Site**: https://hotmovs.com/videos/4000789/mandy-muse-in-biker-chick-mandy-anally-manhandled-evilangel/

**Issue**: Please remove the ad banner on the player.

**Screenshot**: http://prntscr.com/mpe3sw

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Fixed

**Comment by Nzzyme** [comment]
Hello, still seeing ad banner on video player
https://hotmovs.com/videos/126180/sexy-aged-indian-aunty/

http://prntscr.com/o55uns

Seen on AG for Chrome

**Comment by BlazDT** [comment]
Fixed an ad text and stealth issue which resulted in video not playing.

It seems the shown element sometimes does not have the ID, but always the class name, changed it.

It seems the screenshot site does not like all my devices as they only show the ads when unblocked, but not the good picture. I always have to dig the picture via console due to this error:

Access to image at 'https://image.prntscr.com/image/7i9CNqQ9SialysPK9-k5nw.png' from origin 'https://prnt.sc' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Nzzyme** [comment]
My current Stealth Settings:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled

Regarding the screenshot, are you finally able to view the picture or not? I checked quickly on the web for "CORS policy" and it seems you use this "https://alfilatov.com/posts/run-chrome-without-cors/" but I am not sure.

**Comment by BlazDT** [comment]
I was able to see it via console. Since FireFox, Edge etc. also are not showing the picture, it is not that element. But it seems now the screenshots work again (without changing something on my end).

If you try the rules I added, it should work for you (or you wait about three hours after the commit and update filter lists).

**Comment by Nzzyme** [comment]
Pop-up seen when clicking on the play button

https://hotmovs.com/videos/4013401/sheridan-love-logan-long-myfriendshotmom/

Moreover, video does not play when AG is enabled

Please fix

**Comment by BlazDT** [comment]
Not reproduced, please check @AdamWr

**Comment by AdamWr** [comment]
Fixed.
