### ISSUE TITLE
i24news.tv

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#140852]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.54

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.i24news.tv/en/news/ukraine-conflict/1674409784-morocco-gives-tanks-to-ukraine-report

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>

![2023-1-24_15-45-41](https://user-images.githubusercontent.com/29574622/214260497-4cf8a8f3-6c9e-420c-bcd4-65429a4137f0.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by SeriousHoax** [comment]
> Fixed, update should be available in 1-2 hours.

I'm still seeing it in Adguard for Android + Chrome with Cloudflare dns. 
Can you please check?

**Comment by zloyden** [comment]
I've updated the rule, so the leftover is blocked. Update the filters in 1-2 hours.

Mobile app banner has been hidden fine on my end. If you still see it, clear browser data, restart the browser, open the site. Do this after checking the filter update.
