### ISSUE TITLE
[Android] Buffer app can't connect to servers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1442]
[This](https://play.google.com/store/apps/details?id=org.buffer.android&hl=en).

Disabling ad filtering in the firewall helped. Can we fix it? Do we need any logs or something?

BHD-434-96166

**Comment by evgeniy-ADG** [comment]
The same issue with [this](https://play.google.com/store/apps/details?id=tv.periscope.android&hl=en) app, solved in pref.net.exclusions.

**Comment by Alex-302** [comment]
I don't have problems with Periscope

He can try to disable all filters and check again. If the problem not solved, file a bug.

**Comment by Alex-302** [comment]
For Buffer app please check these rules(added to Mobile filter):
```
@@||api.bufferapp.com/*/user
@@||api.bufferapp.com/*/profiles.json
@@||api.bufferapp.com/*/service/
```
If the problem will solved, close this issue
