### ISSUE TITLE
mobile.donanimhaber.com

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#14757]
@Alex-302 
I guess this rule does not work.

`mobile.donanimhaber.com##div[style="margin:10px auto; text-align:center; width:320px; height:100px;"]`

Sometimes the advert space at the top is coming back up and then disappear.

https://mobile.donanimhaber.com/

Screen video
https://streamable.com/isknj

https://forum.adguard.com/index.php?threads/resolved-mobile-donanimhaber-com-ios-safari-banner-ad.24482/#post-149626

Information                            | Value
---                                    | ---
Operating system version  | iOS 
Browser:                               | Safari
AdGuard version:                       | 2.0.4
Filters enabled:                       | English - Spyware - Annoyance - Social Media - Turkish - Mobile Ads - Safari filter - NoCoin
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 

![asset](https://user-images.githubusercontent.com/34379403/38757147-9e66d58c-3f74-11e8-8579-3658ad270a62.JPG)

**Comment by BlazDT** [comment]
Please try this rule:

`mobile.donanimhaber.com##body > .content > div[style*="width: 100%"][style*="background-color"]:not([id]):not([class])`

**Comment by PentagramTr** [comment]
@BlazDT 
It's not working.

**Comment by PentagramTr** [comment]
@BlazDT 
Are you talking about this space?

![github com](https://user-images.githubusercontent.com/34379403/38832738-2dc4e97c-41cc-11e8-828b-506895d64c00.png)


`mobile.donanimhaber.com##body > .content > div[style*="width:100%"][style*="background-color"]:not([id]):not([class])`

If yes,I tried but still not working.

**Comment by PentagramTr** [comment]
@Alex-302 Can you please check this issue?

**Comment by Alex-302** [comment]
fixed

**Comment by PentagramTr** [comment]
@Alex-302 
It did not work.I still see the advert space.Can you please delete the last 2 rules added to the mobile filter?No more need these rules.
Thanks

<details><summary>Screenshot:</summary>

![www google com tr](https://user-images.githubusercontent.com/34379403/39438366-9b9ad458-4cac-11e8-9113-12223fdd5009.png)

**Comment by PentagramTr** [comment]
@BlazDT 

Could you add these rules to the mobile filter?
Thanks.

---
Ad leftover
https://mobile.donanimhaber.com/

`mobile.donanimhaber.com##div[style="margin: 10px auto; text-align: center; width: 320px; height: 100px;"]`

**This new revised rule is blocking the empty space above.**

<details><summary>Screenshot:</summary>

![38757147-9e66d58c-3f74-11e8-8579-3658ad270a62](https://user-images.githubusercontent.com/34379403/41503412-4d8b97b6-71dc-11e8-9dad-13bdcc1d972d.JPG)


</details>

---

Ad leftover
https://mobile.donanimhaber.com/new-york-ataturk-caddesi--133359494

`mobile.donanimhaber.com###news-container`

<details><summary>Screenshot:</summary>

![img_4485](https://user-images.githubusercontent.com/34379403/41503399-009892ec-71dc-11e8-94c6-0e8326426baa.jpg)


</details>

---


Sponsored content
https://mobile.donanimhaber.com/forumid_462/tt.htm

`mobile.donanimhaber.com##.yazilim-sponsor`

<details><summary>Screenshot:</summary>

![img_4484](https://user-images.githubusercontent.com/34379403/41503403-0f434062-71dc-11e8-9b24-b8618c7cdbba.jpg)


</details>

---

/ads/j.js  (If have mistake in the rule, can you rewrite it?)
`||mobile.donanimhaber.com/ads/`

<details><summary>Screenshot:</summary>

![ads](https://user-images.githubusercontent.com/34379403/41503350-3614de82-71da-11e8-93e1-2815e2d6ba48.png)



</details>

**Comment by BlazDT** [comment]
First element is already hidden by mobile ads filter:
mobile.donanimhaber.com##.content > div[style*="text-align: center; width: 320px; height: 100px;"]

Other rules added with a few additional options.
