### ISSUE TITLE
repubblica.it

### ISSUE THREAD

**Issue by antonioditravazzano** [AdguardTeam/AdguardFilters#149598]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I made sure all content blockers are enabled in Safari settings
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.6(998)

### Environment

```markdown
- OS:Ventura 13.3.1
- Safari version:16.4
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.open "la Repubblica"
2.login
3.open section podcast
4.click on the selected podcast
5. the podcast start but no audio

### Expected Behavior

open section podcast
click on the selected podcast
 the podcast start but no audio

### Actual Behavior

open section podcast
click on the selected podcast
the podcast start with audio

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Alex-302** [comment]
@antonioditravazzano Please send report as described here https://adguard.com/kb/guides/report-website/

**Comment by Alex-302** [comment]
Fixed a problems here
https://www.repubblica.it/podcast/la-giornata/

**Comment by ihurin** [comment]
Hi there,
I've got a customer saying the issue is still caused by AdGuard Tracking Protection filter. 
<img width="408" alt="Screenshot 2023-05-01 at 12 04 15" src="https://user-images.githubusercontent.com/33690072/235432624-0a9bf8f0-a17b-4d4c-b6cb-f1b42d9cadbd.png">

**Comment by ihurin** [comment]
@Alex-302 can you check it please?

**Comment by ihurin** [comment]
@Alex-302 can you please check?

**Comment by antonioditravazzano** [comment]
the website that is working wrong with the filter enabled is www.repubblica.it

**Comment by Alex-302** [comment]
Added one missed rule, but podcast section is not working even without AdGuard

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/235615804-89bd0c8a-e700-4e59-875c-40d43ceb5b1b.png)


</details>

**Comment by Alex-302** [comment]
Checked with Italian VPN - it works in Safari with `AdGuard for Safari` or with `AdGuard for Mac`.
Which versions of enabled filters?
