### ISSUE TITLE
sonixgvn.net

### ISSUE THREAD

**Issue by dtantono** [AdguardTeam/AdguardFilters#186942]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker

### AdGuard version

Version 4.3.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://sonixgvn.net/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. I know there was an issue [before](https://github.com/AdguardTeam/AdguardFilters/issues/166320). But, it looks like it cover whole screen instead. What do you think?

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="954" alt="image" src="https://github.com/user-attachments/assets/6c390ba6-9db3-4eb6-828a-2450309ff148">

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

**Comment by moemoe900** [comment]
@AdamWr Sorry, When I installed the extension. it looks like the problem persists

**Comment by AdamWr** [comment]
I see, it looks like that they changed their anti-adblock script again.
Fixed again.

You can add these rules:
```adblock
@@/https?:\/\/(www\.)?sonixgvn\.net\/.{1,15}\.js$/$script,~third-party,domain=sonixgvn.net
sonixgvn.net#%#//scriptlet('prevent-addEventListener', 'DOMContentLoaded', 'overlays')
```
to user rules until filters update will be available.

**Comment by moemoe900** [comment]
@AdamWr Thanks for an update. But, it looks like it does not worked again

**Comment by AdamWr** [comment]
Fixed again, filters update should be available in 1-2 hours.

**Comment by AdamWr** [comment]
I have updated rules (filters update should be available now), but on my end anti-adblock notice looked the same as previously.

**Comment by moemoe900** [comment]
@AdamWr since this is a filehosting site. I can see that the download URL is covered by ads. Is it possible for the adblocker to not cover this element?
ie: https://sonixgvn.net/zettai-meirei-isekai-soushin-party-theme-song-cd/

**Comment by moemoe900** [comment]
@AdamWr it looks like there is a change that it looks like it shows different URLs when I disabled the extension or enabled the extension. Example:

Extension enabled shows
https://sonixgvn.net/dark/?
Extension disabled shows 
https://sonixgvn.net/dark/?aHR0cHM6Ly9yaW5rdS5tZS80SGRRbg

**Comment by moemoe900** [comment]
@AdamWr it looks like the URL  on the blue box is totally different  when I disabled the extension or enabled the extension. Example:

Extension enabled shows
https://sonixgvn.net/dark/?
Extension disabled shows 
https://sonixgvn.net/dark/?aHR0cHM6Ly9yaW5rdS5tZS80SGRRbg
Is it possible to make the real URL visible?

**Comment by AdamWr** [comment]
I'm not sure from which link is this URL (`https://sonixgvn.net/dark/?aHR0cHM6Ly9yaW5rdS5tZS80SGRRbg`), but I have checked it out on the link from https://github.com/AdguardTeam/AdguardFilters/issues/186942#issuecomment-2323090873 (`https://sonixgvn.net/zettai-meirei-isekai-soushin-party-theme-song-cd/`) and I could not reproduce it.
<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/c98e49b3-5f6e-48f1-bdea-d6761bc4f842)

</details>

**Comment by moemoe900** [comment]
Thanks, it works. But, after the website direct me to redirector website. it looks the adblock blocker shows up.
https://beautifulfashionnailart.com/bypass.php
![2024-09-22_10-20](https://github.com/user-attachments/assets/eebee8ac-0887-49d1-940c-c250f6d8bc1a)

**Comment by AdamWr** [comment]
>sometimes it bounces me back to main website

It should be fixed already (at least until something will be changed on the website again), but I couldn't reproduce problem like on the screenshot.

**Comment by moemoe900** [comment]
Hi
I tested on 2 different browsers. on Chromium, it works okay. But on Firefox. the blue box is gone unless I disable the extension. What do you think?
https://sonixgvn.net/zettai-meirei-isekai-soushin-party-theme-song-cd/

<img width="863" alt="363480093-9a012a61-b53e-44f6-9a0c-0fc6ac4fa2c8" src="https://github.com/user-attachments/assets/fb02ec34-e3ee-490c-a1a2-8da23e2f11e4">
<img width="760" alt="363480068-eea7cb1c-dbb3-4f47-b649-dcfece1b4b81" src="https://github.com/user-attachments/assets/a021f292-bc36-48aa-9a1d-ede8d8636348">

**Comment by AdamWr** [comment]
To be honest, I don't know, because I cannot reproduce it (I see this blue box with links in Firefox and in Chrome).

<details><summary>Firefox</summary>

![image](https://github.com/user-attachments/assets/c16dad7b-caf0-401c-bab5-9a4460fd90a2)

</details>

<details><summary>Chrome</summary>

![image](https://github.com/user-attachments/assets/ff86e6d2-89f7-413c-8238-30add4f35a7c)

</details>

Maybe filter lists are not up to date, or perhaps it's caused by third-party filter list.

**Comment by moemoe900** [comment]
it looks for the URL like this https://sonixgvn.net/dark/?aHR0cHM6Ly9yaW5rdS5tZS9RU0VsNHk
The ads are still shown. What do you think?

![image](https://github.com/user-attachments/assets/ecbfefcf-200d-4738-af28-8b20e9c26a26)

**Comment by AdamWr** [comment]
I cannot reproduce ads.
It looks like AdGuard is disabled or website was opened before extension was initialized.

**Comment by moemoe900** [comment]
Yes, I restart the adguard extension again and it looks like the adblock blocker is back again.
![2024-09-27_20-44_1](https://github.com/user-attachments/assets/ec1fe42f-bad3-4086-b6e6-fc5935922739)
![2024-09-27_20-44](https://github.com/user-attachments/assets/3b1d36bf-7060-4a4a-9c8e-f5d7180b7853)
![2024-09-27_20-43](https://github.com/user-attachments/assets/4455156f-d209-4664-98eb-a4aea17b9a36)

**Comment by moemoe900** [comment]
@AdamWr it looks like the adblock blocker is coming up again. What do you think?
![2025-01-15_23-44](https://github.com/user-attachments/assets/8a8c70ac-04e2-44e5-8fd9-b5d534d5bc58)

**Comment by AdamWr** [comment]
I have added new rules, but in the case of MV3 extension it will be available in the next extension version.
