### ISSUE TITLE
winporn.com [NSFW] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19392]
**Site**: https://www.winporn.com/video/326977/dick-slurping-whore-is-excited-to-give-head-and-get-pounded-hard

**Issue**: Please remove the empty Ad banner at the bottom of the page.
 
**Screenshot**: http://prntscr.com/k3vxu2

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not shown, can you still reproduce?

**Comment by Nzzyme** [comment]
I am on the Android for the time being and see Advertisement text strings on the page. Can you check that. I will check on the PC when I get a chance.

**Comment by BlazDT** [comment]
Fixed mobile version.

**Comment by Nzzyme** [comment]
I am still seeing ad banner and pop-up when clicking on play

https://www.winporn.com/video/524355/elle-en-veut-la-beurette

http://prntscr.com/m68yme

**Comment by BlazDT** [comment]
@AdamWr please check.

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce it even without AdGuard.

**Comment by Nzzyme** [comment]
Can you try this?

https://www.hidemyass-freeproxy.com/proxy/en-in/aHR0cHM6Ly93d3cud2lucG9ybi5jb20vdmlkZW8vNTc4NDE4L2Rlc2ktaW5kaWFuLXlvdW5nLWJsb3dqb2ItYW5kLWhhcmQtcmlkaW5nLWZyZWUtcG9ybi1zZXgtYXNz

You can see the banner on the bottom right of the page.

**Comment by BlazDT** [comment]
Seeing via mentioned link, fixed as generic rule (EasyList already contains a few containing that ID and generic rule is already in Liste FR which our French filter is based on).

**Comment by Nzzyme** [comment]
Ad text strings seen on this page:
https://www.winporn.com/video/599298/tattiana-with-big-hot-boobs-has-a-penis-watch-her-jerk#

http://prntscr.com/owthiz

**Comment by BlazDT** [comment]
Please post screenshot on github, not seeing ads.

**Comment by Nzzyme** [comment]
Done

**Comment by BlazDT** [comment]
Thank you, seen on another device. Fixed.
