### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by MatzFan** [AdguardTeam/AdguardFilters#20121]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Banner and sidebar ad images
* **Current behaviour**: Images visible with Adguard filters active

With 

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image]
![image](https://user-images.githubusercontent.com/3764715/43084916-87e6cd32-8e91-11e8-9886-ae74f1a8d930.png)

</details><br/>

* **Expected behaviour**: 

Images should not be visible
<details><summary>Screenshot:</summary>

![image]
![image](https://user-images.githubusercontent.com/3764715/43085060-e6dc1c52-8e91-11e8-8ea1-0db31076680b.png)

</details><br/>

***Steps to reproduce the problem***:

Navigate to www.haaretz.com

***System configuration***

**Filters:**

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Linux Ubuntu 18.04
Operating system version (Android/iOS) |
Browser:                               | Chromium 67.0.3396.99
AdGuard version:                       | 2.9.2
Filters enabled:                       | All
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**The following custom filter resolves the issue**

`||www.haaretz.com/st/media/Houdini/content/*`

**Comment by BlazDT** [comment]
Fixed, please list your filters next time, thank you.

**Comment by MatzFan** [comment]
Thanks, but I just added those 2 exceptions and I'm still seeing the offending images. Any reason you can't use the one I suggested; `||www.haaretz.com/st/media/Houdini/content/*`, instead of exceptions?

FWIW the adblock countermeasure script responsible for this is at https://www.haaretz.com/st/cdn/myhoudini.js?version.82

**Comment by BlazDT** [comment]
That script is not requested here and some (probably nearly the complete content of it) has the main page when I visit it.
It is better to combat the origin of a problem and not the result. Also the rule can cause false positives.

With usual filters on Chrome/FireFox Extension I can't reproduce after adding the exceptions rules. Did you clean your browser cache? This is an important step for this site.

**Comment by MatzFan** [comment]
Interesting. Visiting the page for the first time does not show the images now, but refreshing the page even with the cache cleared does. Looking at the 'myhoudini' countermeasure script it seems to be because of the following value set in local storage `adblockdetect : true`. If I clear that & refresh no images. Given this behavior, I still think it may be work blocking the images at source - or the offending js. I'll keep my custom filter if you decide otherwise. Thanks for looking at this one either way.

**Comment by BlazDT** [comment]
I added a javascript rule as a backup.
