### ISSUE TITLE
combi.de

### ISSUE THREAD

**Issue by Fabian42** [AdguardTeam/AdguardFilters#210395]
### Prerequisites

- [x] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [x] Filters were updated before reproducing an issue;
- [x] AdGuard product version is up-to-date;
- [x] Browser version is up-to-date;
- [x] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

-

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

combi.de

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

The cookie banner on combi.de cannot be closed when this rule is active:
`combi.de#$#body { overflow: auto !important; }`
It's included in "AdGuard – Cookie Notices". With that filter off, the website works.
I'm using uBlock, which has that as one of its selectable filter lists.
None of the three buttons do anything. (It also terribly blurs the website, which hurts my eyes. I guess I should complain to the website owners as well).

Screenshot:
<img width="2176" height="1267" alt="Image" src="https://github.com/user-attachments/assets/af1cee51-f45a-4577-942b-6b01c112aec8" />

### Privacy

- [x] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.

**Comment by Fabian42** [comment]
The cookie notice still appears, but at least the buttons work now.

**Comment by zloyden** [comment]
The cookies are blocked, but uBlock Origin does not accept some types of our rules. I've added another ones for it that seems to be fine on my end. Update should be available soon. If there are problems with these rules, they will have to be removed.
