### ISSUE TITLE
torrentz2eu.top [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21298]
**Site**: https://torrentz2eu.top/

**Issue**: Please remove the pop-up on the page.
 
**Screenshot**: http://prntscr.com/kkd77i

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Still happening?

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
Just checked on Android and still seeing the popup. Will thw rule not work for Android?
