### ISSUE TITLE
timesofindia.indiatimes.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26978]
**Site**: https://timesofindia.indiatimes.com/india/shah-questions-rahuls-sinister-campaign-against-rafale-deal/articleshow/67100650.cms

**Issue**: After opening the page, scroll down a little until you arrive at the section named "From Around the Web". The links under this section are ads. Can you remove this entire section.

**Screenshot**: http://prntscr.com/lv9zfz

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
Not fixed. Still seeing empty ad boxes

http://prntscr.com/ms8wqc
