### ISSUE TITLE
bild.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3404]
**Site**: http://www.bild.de/
**Description**: Ad leftover.

**Current behaviour**: Site has some ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20238548/97d86e6a-a8ee-11e6-86b5-9f52eda9c9c6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20238555/b42759f0-a8ee-11e6-988c-09623589ba1d.png)

And a few more...

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.29
Spyware filter 1.0.8.94
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.69
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by seanl-adg** [comment]
Can't reproduce now. Maybe it has been fixed earlier.

**Comment by danidoedel** [comment]
@seanl-adg Not fixed.
![image](https://cloud.githubusercontent.com/assets/10995998/20301355/47c3449a-ab23-11e6-8d40-17fa89485ddf.png)
![image](https://cloud.githubusercontent.com/assets/10995998/20301373/5743cf16-ab23-11e6-9972-40a4cd8e1376.png)
![image](https://cloud.githubusercontent.com/assets/10995998/20301388/67f70c10-ab23-11e6-8b44-ae9fa0aa28c4.png)

**Comment by seanl-adg** [comment]
Still can't reproduce, but I've added a hiding rule according to screenshots.

**Comment by danidoedel** [comment]
@seanl-adg @Alex-302  That issue still happens and I figured out which rules cause this problem... It's `@@||bild.de^$elemhide` or `@@||sascdn.com^$domain=bild.de,script` (Not sure why disabling one or both of them resolve the problem though) in Mobile and Safari filter. Not sure what that rule does and what it's needed for.
I hope this can be fixed somehow.

**Comment by Alex-302** [comment]
> @||bild.de^$elemhide

it is against anti-adblock. Try to disable and add
```
@@||bild.de^$generichide
```

**Comment by danidoedel** [comment]
@Alex-302 Yeah that seems to work.

There is still some ad leftover on that site:

![image](https://cloud.githubusercontent.com/assets/10995998/20463859/9fb02a16-af3c-11e6-96f4-bd9c3e54ad42.png)

**And mobile:**

![image](https://cloud.githubusercontent.com/assets/10995998/20463847/7877779c-af3c-11e6-84f0-3d973d29603a.png)


![image](https://cloud.githubusercontent.com/assets/10995998/20463833/482bb18e-af3c-11e6-9393-b465d9147690.png)


![image](https://cloud.githubusercontent.com/assets/10995998/20463828/334e314c-af3c-11e6-9ba6-0943196e6cfd.png)

**Comment by Alex-302** [comment]
I see only the first(game ad)
```
bild.de##.partnerfont
```
