### ISSUE TITLE
www.aftonbladet.se - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3719]
***Description***: Preroll ads on the website:
http://www.aftonbladet.se/nyheter/a/Vvr6p/en-allvarligt-skadad-efter-luciafirande-pa-vattnet

***System configuration*** | value
--- | ---
Operating system: | Mac OS 10.12
Browser: | Chrome
Adguard version: | 1.3.0
Adguard filters: | User, English, Spyware, Social Media, Fanboy's Swedish (Reproduced with basic ones) 

Ticket ID(if exists): 1112256

**Comment by Alex-302** [comment]
Fixed(not for browser extensions)

**Comment by dzamyshlyayeva** [comment]
the issue is back: preroll ad before the video

<details>

![](https://files.slack.com/files-pri/T02BTRFDB-F5K15S6N6/image_uploaded_from_ios.jpg)

</details>

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.57 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.17 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.56 Enabled=NO
ID=223 Name="Fanboy's Swedish" Version=1.0.0.5 Enabled=YES

ticket ID:1566135

**Comment by Alex-302** [comment]
@dzamyshlyayeva original issue is about Mac OS.
We can't block this preroll on iOS.
