### ISSUE TITLE
gdata-software.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#44534]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Cookie notice

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29574622/69416597-2ac7e480-0d41-11ea-95dd-6de498efce19.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)
Shouldn't be a cookie notice
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
Adguard base list, Adguard tracking protection, Adguard annoyances, Adguard social media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1909
Browser:                               | Firefox Developer Edition 71 beta 11
AdGuard version:                       | 
Filters enabled:                       | Adguard base list, Adguard tracking protection, Adguard annoyances, Adguard social media
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          | 
AdGuard DNS:                           | 
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by slavaleleka** [comment]
fixed. filter updates will be available in a few hours as usual

**Comment by SeriousHoax** [comment]
@slavaleleka More than 18 hours have passed and not fixed yet. Can you check again please?

**Comment by slavaleleka** [comment]
@SeriousHoax I've checked and there is no cookie notice now. make sure that your browser is filtered by AdGuard and check for updates manually please

**Comment by SeriousHoax** [comment]
> 
> 
> @SeriousHoax I've checked and there is no cookie notice now. make sure that your browser is filtered by AdGuard and check for updates manually please

Hello, sorry to bother you again. It was gone after your last reply but it's appearing again. I'm not using the Adguard desktop app I'm using the filters Adguard base list, Adguard tracking protection, Adguard annoyances, Adguard social media filters in uBlock Origin in Firefox and Brave and Adguard in Edge. I tried with 3 different browsers and the cookie notice is present in every one of them.

**Comment by slavaleleka** [comment]
@SeriousHoax could you please add to User rules such one?
`gdata-software.com###gd-cookiebar `

**Comment by SeriousHoax** [comment]
> 
> 
> @SeriousHoax could you please add to User rules such one?
> `gdata-software.com###gd-cookiebar `

Hi, sorry actually I made a mistake. gdata-software works but I didn't notie they made another simplified domain without the (-) in the middle. So, it's https://www.gdatasoftware.com/ 

Can you commit this?
