### ISSUE TITLE
Anti Ad-Block on http://www.apkmirror.com/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5040]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Open this link:  http://www.apkmirror.com/apk/google-inc/google/google-9-12-0-155676601-release/google-9-12-0-155676601-android-apk-download/

Reproduced on Android only

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/26246242/baa2b568-3ca0-11e7-8715-3bed33d4f933.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.7
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | Russian, English, Spyware, Social media, Annoyances, Mobile Ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1558833

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It was fixed yesterday.

**Comment by TPS** [comment]
@Alex-302 This is _still_ not fixed, with identical behavior, as of a few minutes ago.  Did fix not get published?

**Comment by Alex-302** [comment]
Check:
```
apkmirror.com#@#.google-ad-leaderboard-smaller
apkmirror.com#@#.google-ad-square-sidebar
apkmirror.com#@#.gooWidget 
```

**Comment by TPS** [comment]
Looks ok now;  maybe it was just a filterlist update delay.  Though, if you let the page sit for a while (like if 1 loads the page, then immediately switches to another app, then switch back), the delay seems to reappear.… 🤷

Thanks for checking on it, @Alex-302. 👏

**Comment by TPS** [comment]
@Alex-302 Broken, again, & if page allowed to sit for some time.  Please reinvestigate.

P.S.: While looking for this issue, ran into https://adguard.com/en/adguard-report/apkmirror.com/report.html .  VERY nice!  Is this something that'll be incorporated into mobile, as well?

**Comment by Alex-302** [comment]
Not reproduced. I don't know your config.
