### ISSUE TITLE
anti-adblock script https://www.firstonetv.eu/Live/United-Kingdom/BBC-News-2

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5266]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
anti-adblock script https://www.firstonetv.eu/Live/United-Kingdom/BBC-News-2

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26779628/cef55f9c-49ee-11e7-972c-2841cdda778e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | chrome
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental
Ticket ID (if exists): | 1406620

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by ypetruk** [comment]
the issue still takes place on https://www.firstonetv.eu/Live/United-Kingdom/BBC-News-2

<details>

![screen shot 2017-06-11 at 1 08 41 pm](https://user-images.githubusercontent.com/28784344/27010174-1da6f76a-4ea7-11e7-812a-e1897e8bc1cc.png)

<\details>

**Comment by Alex-302** [comment]
Fixed
