### ISSUE TITLE
Edge Legacy not filtered in certain conditions

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#56644]
### Steps to reproduce

1. Subscribe for AdGuard Base filter, AdGuard Annoyances filter, AdGuard German filter
2. Open Microsoft Edge Legacy
3. Browse https://www.computerbase.de/ -> it will be filtered
4. Reload the page -> it won't be filtered anymore

There are 2 filtered entrys, but this is far from this, what is in the Adguard Filterlists.

When I use Internet Explorer of Firefox and reload the page -> it is always filtered fine.
When I browse another page and reload on Edge Legacy -> they will be also filtered.

So the issue is somehow the combination of Edge Legacy and this page. Maybe there are also other pages.

Check the video.

### Expected behavior

To have filtered pages all the time.
### Actual behavior

Ads and Banners passthrough Adguard on Edge Legacy.

Video:

[2020-05-26 17-51-15.zip](https://github.com/AdguardTeam/AdguardForWindows/files/4683577/2020-05-26.17-51-15.zip)

The real issue is shown at 0:50.

</details>

### Customer ID 

There is no gear in the main window. Don't know what you want here, but here is the Debug Log when I reproduced the issue:

[adg_logs_7.4.3232.0_0526_1755.zip](https://github.com/AdguardTeam/AdguardForWindows/files/4683553/adg_logs_7.4.3232.0_0526_1755.zip)

### Your environment

* Environment name and version: Microsoft Edge 44.19041.1.0 Microsoft EdgeHTML 18.19041
* Operating system and version: Windows 10 x64 v. 2004 Build 19041.264
* Adguard: 7.4.3232.0, also had the issue with Adguard 7.3

**Comment by Alex-302** [comment]
I have no Edge Legacy. @AdguardTeam/filters-maintainers please take a look.

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers

**Comment by AdamWr** [comment]
I don't have Edge Legacy either.
I might be wrong, but if it works fine in other browsers and it works fine on first visit in Edge Legacy, then I think it's not a filter lists issue.

**Comment by Morku** [comment]
I don't think it's a filterissue either, thats why I created the ticket at AdGuard for Windows.
Still, I can reproduce the issue with AdGuard 7.4.2.

So if you need remote assist or whatever...

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #3360](https://github.com/AdguardTeam/AdguardForWindows/issues/3360) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Ok, moved to AdGuard for Windows

**Comment by ameshkov** [comment]
Guys, this is caused by the service worker.

I suggest you block it there:
https://uploads.adguard.com/up04_Windows_10_e8tlj.png

**Comment by Morku** [comment]
@AdamWr 
If the changes should fix the issue, it doesn't :(
My filters within the changes are current.

After reloading the page with Edge Legacy, all Ads and Banners passthrough AdGuard.

**Comment by AdamWr** [comment]
Could you please check if issue still occur if you add this rule to user filter:
```
computerbase.de#%#navigator.serviceWorker.getRegistrations().then( function(registrations) { for(let registration of registrations) { registration.unregister(); } });
```

**Comment by Morku** [comment]
@AdamWr 
Does not work.

**Comment by AdamWr** [comment]
Could you please press `F12` go to `service workers` and click on `unregister` button.
Something like on a screenshot below (I'm not sure how it looks in Edge Legacy, but I hope that it looks similar). Then please check if it still happens.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/84187682-b3fef880-aa92-11ea-84db-624c0b682916.png)

</details>

**Comment by Morku** [comment]
@AdamWr 
There is. On first visit -> No Serviceworker found
I reload the page -> full of Ads and there is a Service worker
When I click unregister (aufheben in german) and reload -> the Ads are gone
Then I reload again -> Serviceworker and Ads are back

As usual, a video explains best I think:

[2020-06-09 20-54-35.zip](https://github.com/AdguardTeam/AdguardFilters/files/4754254/2020-06-09.20-54-35.zip)

**Comment by AdamWr** [comment]
Ok, I added another rule which should fixes it:
`computerbase.de#%#//scriptlet("prevent-addEventListener", "load", "/service-worker.js")`
Update should be available in 1-2 hours.
But it will be necessary to unregister service worker.

**Comment by Morku** [comment]
I can confirm, it is working.
Interesting, I get surprised everytime :)

**Comment by AdamWr** [comment]
Ok, thank you for checking it.
