### ISSUE TITLE
http://werbung.qs-optiker.de/ -German filter breaks the website

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5665]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://werbung.qs-optiker.de/ - German filter prevents the website from loading 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

![screen shot 2017-07-12 at 3 19 22 pm](https://user-images.githubusercontent.com/23372054/28117303-89ddb67c-6715-11e7-97fd-6a76e9e51524.png)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Operating system:  Windows / Mac OS 
Ticket ID: 1590858

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by qsoptiker** [comment]
issue something with html elements??

**Comment by danidoedel** [comment]
Issue caused by this rule in German filter: `/werbung.$~image,~stylesheet,domain=~berlin-airport.de`
Should be modified in: `/werbung.$~image,~stylesheet,domain=~berlin-airport.de|~qs-optiker.de`

**Comment by qsoptiker** [comment]
who will modify the filter?

**Comment by danidoedel** [comment]
Someone of the filter devs (@Alex-302, @seanl-adg or @AdamWr) will do that.

**Comment by qsoptiker** [comment]
do you when? and will we get nofitied? 

because we got a big marketing campagin starting tomorrow, and then many people will visit our site..

thanks for your support @danidoedel !!!!

**Comment by dzamyshlyayeva** [comment]
our Support Team will let you know as soon as the issue is solved.

**Comment by qsoptiker** [comment]
ok, thank you guys!

**Comment by Alex-302** [comment]
Fixed.

**Comment by qsoptiker** [comment]
..still not loading

![image](https://user-images.githubusercontent.com/30117547/28124597-6cfcbe4a-6724-11e7-89e5-dbd8adefa746.png)

**Comment by danidoedel** [comment]
You have to wait for the filters to update. Happens every hour when changes were made, not sure when exactly though.

**Comment by qsoptiker** [comment]
thank you guys!

**Comment by qsoptiker** [comment]
still not working. sorry guys...

**Comment by qsoptiker** [comment]
our said also gets blocked by adblock plus, friends told me

i think issue is because of html elements of wordpress / wordpress theme....

**Comment by qsoptiker** [comment]
it says 35 commercials blocked...

![image](https://user-images.githubusercontent.com/30117547/28156207-110c455e-67b2-11e7-8061-4da458cf04db.png)

**Comment by danidoedel** [comment]
Update your filters. It is working with the latest filter. 
No it‘s not html elements, it‘s just a bad idea to name your subdomain something like „werbung“ or „ad“ or something like that.

**Comment by Alex-302** [comment]
@qsoptiker Hi
I don't see Adguard on your screenshot. Which filters and ad blocker are you using?

**Comment by qsoptiker** [comment]
check marked text...there it says...by Adguard

![image](https://user-images.githubusercontent.com/30117547/28157846-19c89a0c-67b8-11e7-96ac-9783edf11589.png)

**Comment by danidoedel** [comment]
It is the Avira Browser Safety extension

**Comment by qsoptiker** [comment]
@danidoedel thank you, i really dont have any idea about IT...how can i update filter?

**Comment by danidoedel** [comment]
Seems like there is no way to manually update the filters in that extension, but not sure about that...

**Comment by Alex-302** [comment]
@qsoptiker please make screenshots of settings or provide download link. Or use Adguard extension:)

**Comment by danidoedel** [comment]
@Alex-302 [Download link](https://chrome.google.com/webstore/detail/avira-browser-safety/flliilndjeohchalpbbcdekjklbdgfkk)

**Comment by qsoptiker** [comment]
![image](https://user-images.githubusercontent.com/30117547/28159035-ece41fda-67bb-11e7-98bb-ebaf6b750f83.png)

**Comment by Alex-302** [comment]
It does not work in my browser.
Please click on the gear icon and make screenshots.

**Comment by danidoedel** [comment]
That‘s what his last screenshot shows. No option to update the filters.

**Comment by qsoptiker** [comment]
@Alex-302 this is screenshot of gear icon...

**Comment by Alex-302** [comment]
I can't help you. Maybe this extension can't update filters or doing it rarely.
You can install Adguard, disable Avira extension and check this site. It works as expected.

**Comment by qsoptiker** [comment]
thank you guys! really appreciate your support. will continue...

have a good time :)
