### ISSUE TITLE
debridnet.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5761]
***Site***: http://debridnet.com/ -> http://debridnet.com/ad-blocker
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28337274-6a13b054-6c05-11e7-962e-0531fad31648.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.15
Spyware filter | 1.0.13.34
Social media filter | 1.0.21.20
Annoyances filter | 1.0.15.60
German filter | 1.0.35.67

**Comment by xhamid** [comment]
https://github.com/reek/anti-adblock-killer#instruction

**Comment by danidoedel** [comment]
@xhamid So? That's not how it works here though...

_________________________________________________

Anyway that page does not pop up anymore. But this button is disabled with Adguard enabled:

![image](https://user-images.githubusercontent.com/10995998/28849549-c16e283a-7717-11e7-8f48-de5cc5d6fcc3.png)

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Not fixed...

![image](https://user-images.githubusercontent.com/10995998/28945135-7cf9071c-78a5-11e7-9673-055a84bbfdc1.png)

**Comment by seanl-adg** [comment]
`10px` should've been `100px`

**Comment by danidoedel** [comment]
@seanl-adg Well, maybe I'm doing something wrong, but the adblock detection still triggers after a few seconds for me :(

**Comment by seanl-adg** [comment]
Thank you for keep tracking this issue, the problem was that 100px was still not enough. I've change it to 1000px.

**Comment by xhamid** [comment]
Make anti adblock working again

**Comment by danidoedel** [comment]
Yep, it's back again.

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Fixed.

**Comment by xhamid** [comment]
how i can do ?

**Comment by danidoedel** [comment]
@AdamWr The page is now refreshing after view seconds, so this bar will never reach its end:

![image](https://user-images.githubusercontent.com/10995998/30248440-3e572c00-9628-11e7-9d81-521acc9ef692.png)
