### ISSUE TITLE
http://m.800xs.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6362]
http://m.800xs.net/book_38100/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29497692-3a2cb9bc-85f5-11e7-9406-98438727f7ec.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3.3
Browser: | Safari
Adguard version: | 1.3.0.100
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options(Windows) | 
Adguard filters: | 2 3 4 8 11 12 14 104 219
Ticket ID (if exists): | 1615221

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by kovalenkoi** [comment]
the issue is back.
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.13 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.48 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.58 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.2.11 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.86.57 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.77 Enabled=YES
ID=229 Name="I don't care about cookies" Version=1.0.0.15 Enabled=YES

![image1](https://user-images.githubusercontent.com/30697077/29776465-58aede48-8c11-11e7-97df-42b26062ba87.PNG)

**Comment by Alex-302** [comment]
Fixed.
