### ISSUE TITLE
Goodreads android app infinite requests issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#6618]
Please see: https://github.com/AdguardTeam/AdguardForAndroid/issues/511#issuecomment-326782481

Here's the app: https://play.google.com/store/apps/details?id=com.goodreads

Can we do something about it except adding an exclusion? 
Block ads there in a different way, use $empty rule or something?

**Comment by Alex-302** [comment]
try to block it with `$important,empty`

**Comment by TPS** [comment]
Is this resolved now?

**Comment by Alex-302** [comment]
@vozersky

**Comment by carlylemiii** [comment]
@TPS it's not resolved for me, just refreshed my filters, started the app up, and checked my filtering log in AdGuard. 250 requests blocked and counting...

**Comment by TPS** [comment]
@carlylemiii Try `||quantcount.com$important` in your user filters & see if that DNS-blocks for you.

**Comment by carlylemiii** [comment]
@TPS I added it to my user filter, but I do not use DNS filtering, and it didn't make a difference, so I am unsure if I misunderstood or not.

**Comment by TPS** [comment]
> I do not use DNS filtering

@carlylemiii _There's_ your problem.  Why not?  If you followed https://github.com/AdguardTeam/AdguardForAndroid/issues/511, I found DNS-blocking the most efficient way to stop such apps' insanity, & much of the rest of that issue was when such DNS-blocking unexpectedly failed.

**Comment by Alex-302** [comment]
@vozersky

**Comment by Alex-302** [comment]
@vozersky

**Comment by carlylemiii** [comment]
Did you try? This is so easily reproduced.

**Comment by vozersky** [comment]
@carlylemiii maybe we just have to exclude the app from filtering then, I'll check it again

**Comment by vozersky** [comment]
was not able to rep

**Comment by carlylemiii** [comment]
Just so weird since I did it just now and this has spanned multiple devices now.

**Comment by Alex-302** [comment]
@carlylemiii please try
* fisable all filters
(or)
* disable HTTPS filtering
